# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\1\ConfusionMatrixDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfusionMatrixDialog(object):
    def setupUi(self, ConfusionMatrixDialog):
        ConfusionMatrixDialog.setObjectName("ConfusionMatrixDialog")
        ConfusionMatrixDialog.resize(451, 223)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfusionMatrixDialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 160, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_input = QtWidgets.QLabel(ConfusionMatrixDialog)
        self.label_input.setGeometry(QtCore.QRect(20, 40, 191, 16))
        self.label_input.setObjectName("label_input")
        self.label_outputdir = QtWidgets.QLabel(ConfusionMatrixDialog)
        self.label_outputdir.setGeometry(QtCore.QRect(20, 90, 151, 16))
        self.label_outputdir.setObjectName("label_outputdir")
        self.lineEdit_result = QtWidgets.QLineEdit(ConfusionMatrixDialog)
        self.lineEdit_result.setGeometry(QtCore.QRect(220, 40, 121, 21))
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.btn_browse_result = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_browse_result.setGeometry(QtCore.QRect(350, 40, 81, 28))
        self.btn_browse_result.setObjectName("btn_browse_result")
        self.lineEdit_outputdir = QtWidgets.QLineEdit(ConfusionMatrixDialog)
        self.lineEdit_outputdir.setGeometry(QtCore.QRect(160, 90, 181, 21))
        self.lineEdit_outputdir.setObjectName("lineEdit_outputdir")
        self.btn_browse_outputdir = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_browse_outputdir.setGeometry(QtCore.QRect(350, 90, 81, 28))
        self.btn_browse_outputdir.setObjectName("btn_browse_outputdir")

        self.retranslateUi(ConfusionMatrixDialog)
        self.buttonBox.accepted.connect(ConfusionMatrixDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ConfusionMatrixDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfusionMatrixDialog)

    def retranslateUi(self, ConfusionMatrixDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfusionMatrixDialog.setWindowTitle(_translate("ConfusionMatrixDialog", "Dialog"))
        self.label_input.setText(_translate("ConfusionMatrixDialog", "Evaluation Table (.xlsx)"))
        self.label_outputdir.setText(_translate("ConfusionMatrixDialog", "Output Directory:   "))
        self.btn_browse_result.setText(_translate("ConfusionMatrixDialog", "Browse"))
        self.btn_browse_outputdir.setText(_translate("ConfusionMatrixDialog", "Browse"))
