# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\1\RandomSamplingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RandomSamplingDialog(object):
    def setupUi(self, RandomSamplingDialog):
        RandomSamplingDialog.setObjectName("RandomSamplingDialog")
        RandomSamplingDialog.resize(447, 294)
        self.buttonBox = QtWidgets.QDialogButtonBox(RandomSamplingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 210, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_image_ori = QtWidgets.QLabel(RandomSamplingDialog)
        self.label_image_ori.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.label_image_ori.setObjectName("label_image_ori")
        self.label_sample_num = QtWidgets.QLabel(RandomSamplingDialog)
        self.label_sample_num.setGeometry(QtCore.QRect(20, 30, 111, 16))
        self.label_sample_num.setObjectName("label_sample_num")
        self.lineEdit_image_ori = QtWidgets.QLineEdit(RandomSamplingDialog)
        self.lineEdit_image_ori.setGeometry(QtCore.QRect(150, 80, 191, 21))
        self.lineEdit_image_ori.setObjectName("lineEdit_image_ori")
        self.btn_browse_ori = QtWidgets.QPushButton(RandomSamplingDialog)
        self.btn_browse_ori.setGeometry(QtCore.QRect(350, 80, 81, 28))
        self.btn_browse_ori.setObjectName("btn_browse_ori")
        self.spinBox_sample_num = QtWidgets.QSpinBox(RandomSamplingDialog)
        self.spinBox_sample_num.setGeometry(QtCore.QRect(150, 30, 51, 22))
        self.spinBox_sample_num.setMinimum(1)
        self.spinBox_sample_num.setMaximum(10000)
        self.spinBox_sample_num.setProperty("value", 99)
        self.spinBox_sample_num.setObjectName("spinBox_sample_num")
        self.lineEdit_image_class = QtWidgets.QLineEdit(RandomSamplingDialog)
        self.lineEdit_image_class.setGeometry(QtCore.QRect(150, 120, 191, 21))
        self.lineEdit_image_class.setObjectName("lineEdit_image_class")
        self.btn_browse_class = QtWidgets.QPushButton(RandomSamplingDialog)
        self.btn_browse_class.setGeometry(QtCore.QRect(350, 120, 81, 28))
        self.btn_browse_class.setObjectName("btn_browse_class")
        self.label_image_class = QtWidgets.QLabel(RandomSamplingDialog)
        self.label_image_class.setGeometry(QtCore.QRect(20, 120, 191, 16))
        self.label_image_class.setObjectName("label_image_class")
        self.label_outputdir_2 = QtWidgets.QLabel(RandomSamplingDialog)
        self.label_outputdir_2.setGeometry(QtCore.QRect(20, 160, 151, 16))
        self.label_outputdir_2.setObjectName("label_outputdir_2")
        self.btn_browse_outputdir_2 = QtWidgets.QPushButton(RandomSamplingDialog)
        self.btn_browse_outputdir_2.setGeometry(QtCore.QRect(350, 160, 81, 28))
        self.btn_browse_outputdir_2.setObjectName("btn_browse_outputdir_2")
        self.lineEdit_outputdir_2 = QtWidgets.QLineEdit(RandomSamplingDialog)
        self.lineEdit_outputdir_2.setGeometry(QtCore.QRect(160, 160, 181, 21))
        self.lineEdit_outputdir_2.setObjectName("lineEdit_outputdir_2")

        self.retranslateUi(RandomSamplingDialog)
        self.buttonBox.accepted.connect(RandomSamplingDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(RandomSamplingDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RandomSamplingDialog)

    def retranslateUi(self, RandomSamplingDialog):
        _translate = QtCore.QCoreApplication.translate
        RandomSamplingDialog.setWindowTitle(_translate("RandomSamplingDialog", "RandomSampling"))
        self.label_image_ori.setText(_translate("RandomSamplingDialog", "Original Image:"))
        self.label_sample_num.setText(_translate("RandomSamplingDialog", "Sample Points: "))
        self.btn_browse_ori.setText(_translate("RandomSamplingDialog", "Browse"))
        self.btn_browse_class.setText(_translate("RandomSamplingDialog", "Browse"))
        self.label_image_class.setText(_translate("RandomSamplingDialog", "Class map:"))
        self.label_outputdir_2.setText(_translate("RandomSamplingDialog", "Output Directory:   "))
        self.btn_browse_outputdir_2.setText(_translate("RandomSamplingDialog", "Browse"))
